gh-3: fix typing issues
trag1c/Dahlia pull request #4
Opened 2022-10-05 18:39 UTC by qexat

2022-10-05 18:41 UTC, qexat commented on src/dahlia/dahlia.py
> +    ansi_codes: list[str] = []
@trag1c list or List

2022-10-05 20:22 UTC, trag1c commented on src/dahlia/dahlia.py
> +    ansi_codes: list[str] = []
list

2022-10-05 20:26 UTC, trag1c requested changes

2022-10-05 20:26 UTC, trag1c commented on src/dahlia/dahlia.py
> +]
don't use black79 😩

2022-10-07 12:57 UTC, trag1c approved these changes

2022-10-07 12:58 UTC, merged